import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";



export const metadata: Metadata = {
  title: "Agentic App",
  description: "Generated by suraj",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className="min-h-full w-full flex flex-col">
        <Navbar/>
        <main className="flex-1 w-full flex flex-col items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}